# workflow 的名稱，會在 Github Action 頁面上顯示的名稱（選擇性）
name: Deploy

# 只有在 push 到 main 分支上才會觸發此 workflow
on:
  push:
    branches:
      - main

# 建立一個 job
jobs:
  # 將此 job 的名稱設定為 'build'
  build:
    name: Build
    # 執行在最新版本的 ubuntu runner 上
    runs-on: ubuntu-latest

    steps:
      # 使用 actions/checkout@v3 這個官方的 action
      # 可以查看 workflow 的執行狀況，並對 workflow 的虛擬環境進行指令操作（例如搭建測試環境）
      - name: Checkout repo
        uses: actions/checkout@v3

      # 設定 NODE 環境
      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist